INSERT INTO users (username, password, postcount, logged_in) VALUES ('boxwoodacanthus', 'lemons', 0, 2);
INSERT INTO users (username, password, postcount, logged_in) VALUES ('boxofdreamsandwires', 'fluffy', 0, 2);
INSERT INTO users (username, password, postcount, logged_in) VALUES ('Inceptor', 'rabbits', 0, 2);
INSERT INTO users (username, password, postcount, logged_in) VALUES ('Wrathful', 'righteous', 0, 2);
INSERT INTO users (username, password, postcount, logged_in) VALUES ('A Seal Communion', 'bishop', 0, 2);
INSERT INTO users (username, password, postcount, logged_in) VALUES ('YesYesYes', 'rapture', 0, 2);
INSERT INTO users (username, password, postcount, logged_in) VALUES ('guest', 'guest', 0, 2);


INSERT INTO topics (title, summary, body, images, instaimages, comment_count, comment_update, username) VALUES ('Oyster', 'I ate an oyster. It turned out to be my dad.', 'The title is pretty self-explanatory. This is one of the most disturbing dreams of my life. I can still remember the texture of that oyster. And I split it in half before eating it. Much later I realized it was actually my dad. What does it mean...', "", "", 0, "0", "Inceptor");

INSERT INTO topics (title, summary, body, images, instaimages, comment_count, comment_update, username) VALUES ('Scary red house', 'My family bought a red house, and the walls were pink', 'It was like a little red cabin by the sea. The sea was very blue, the skies were blue-- even the birds were blue, etc etc. I was walking outside of the red house and basically the ground would keep falling away so I felt like I was in this giant rolling meadow/sea/thing except there were spikey plants and it was sort of fuzzy looking but silverish. I thought the red house would eat me, and I would rather the meadow eat me instead. So after we had a fight I ran away from my family into the meadow, and was waiting again for that feeling of everything falling away - so that I could just get swallowed in the earth - but instead nothing happened, it was so still and compact. I just lay there for a long time.', "", "", 0, "0", "Inceptor");

INSERT INTO topics (title, summary, body, images, instaimages, comment_count, comment_update, username) VALUES ("The unopenable garage", "In which the mechanism that controls the door breaks, and everyone ignores it", "I had a dream in which my garage door broke. It is an electric door. No one wants to try to open it by hand, or maybe someone has tried and has figured out that you can't really do it. Different family members come and go, my brother is always lingering around there, but he never goes inside. A long time passes. The door begins to make a scary noise because the wind storms are huge. It's rattling all the time. I've felt horrible this whole dream, and finally I remember that our cat is in the garage, it's probably dead (or maybe died already before the door broke), and this is why no one wants to fix it.", "", "", 0, "0", "A Seal Communion");

INSERT INTO topics (title, summary, body, images, instaimages, comment_count, comment_update, username) VALUES ("nice dream I had", "I thought I was drowning but realized it wasn't a big deal", "I was walking into into the ocean, the water washed all over me, and I was scared at first but instead of drowning I suddenly felt like I could just float and let the water take me wherever I needed to go. Or *swim*.", "", "", 0, "0", "boxofdreamsandwires");

 INSERT INTO topics (title, summary, body, images, instaimages, comment_count, comment_update, username) VALUES ('Interview nightmare', "I've been having a series of recurring nightmares about job interviews...", "Basically it's always like this... I go to a tech interview and they show me a bunch of code, it all looks like: ':3 ^__^ :/'' Omg. I'm like, I dun know that language but maybe I can learn it... they were like, 'No no, it's innate, basically what we're showing you isn't the language *itself* it's just a test... if you have the capacity to do our job you will automatically see some words, if you don't it'll just look like emoticons.' I walk away from their office desolate and sad.", "", "", 0, "0", "YesYesYes");

 INSERT INTO topics (title, summary, body, images, instaimages, comment_count, comment_update, username) VALUES ('NOT A DREAM- Dream-mapping and Dream-translation', "Dream map art projects", "I've been using an REM-mapper to take down dreams into graphs, and running a web app to translate that into a series of glyphs: http://mapdreamsproject.com. You could do the same with language, or music. Right now REM map tech is primative, so you can't do the opposite- take a piece of music, jarble it through the one-to-one dream translator, and see what Thelonious Monk looks like as a dream for instance. But maybe one day we'll get there...", "", "", 0, "0", "Wrathful");